# Model found with optuna
# best f1 score model
input_channel: 3

depth_multiple: 0.25
width_multiple: 1.0

backbone:
    # [repeat, module, args]
    [
        # Conv argument: [out_channel, kernel_size, stride, padding_size]
        # if padding_size is not given or null, the padding_size will be auto adjusted as padding='SAME' in TensorFlow
        [1, DWConv, [16, 3, 1, null, "ReLU"]],
        [1, DWConv, [112, 5, 2, null, "ReLU"]],
        [3, MBConv, [6, 128, 1, 5]],     
        [4, InvertedResidualv2, [128, 7, 1]],
        [2, Conv, [128, 5, 2, null, 1, "Hardswish"]],     
        [1, InvertedResidualv3, [5, 2.5, 16, 1, 0, 1]],
        [1, Conv, [896, 1, 1]],
        [1, GlobalAvgPool, []],
        [1, "FixedConv", [6, 1, 1, null, 1, null]]
    ]