# Model found with optuna
# Similar performance model with less params and f1 score 
input_channel: 3

depth_multiple: 0.25
width_multiple: 1.0

backbone:
    # [repeat, module, args]
    [
        # Conv argument: [out_channel, kernel_size, stride, padding_size]
        # if padding_size is not given or null, the padding_size will be auto adjusted as padding='SAME' in TensorFlow
        [1, DWConv, [16, 3, 1, null, "ReLU"]],
        [1, DWConv, [112, 5, 2, null, "ReLU"]],
        [5, InvertedResidualv2, [64, 6, 1]],
        [3, Conv, [96, 5, 2, null, 1, "Hardswish"]],     
        [1, InvertedResidualv3, [5, 2.5, 64, 1, 0, 1]],
        [1, Conv, [768, 1, 1]],
        [1, GlobalAvgPool, []],
        [1, "FixedConv", [6, 1, 1, null, 1, null]]
    ]