# Model found with optuna by YoonyoungL
# Similar performance model with less params and f1 score 
# number of parameters : 808,016
input_channel: 3

depth_multiple: 0.25
width_multiple: 1.0

backbone:
    # [repeat, module, args]
    [
        # DWConv : [out_channel, kernel_size, stride, padding_size, activation]
        # MBConv : [expand_ratio, out_channel, stride, kernel_size]
        # InvertedResidualv2 : [out_channel, expand_ratio, stride]
        # Conv : [out_channel, kernel_size, stride, padding, groups, activation]
        # InvertedResidualv3 : [kernel_size, expand_ratio, out_channel, use_se, use_hs, stride]
        [1, DWConv, [16, 3, 1, null, "ReLU"]],
        [1, DWConv, [112, 5, 2, null, "ReLU"]],
        [4, MBConv, [6, 128, 1, 5]],     
        [4, InvertedResidualv2, [80, 7, 1]],
        [2, Conv, [144, 5, 2, null, 1, "Hardswish"]],     
        [1, InvertedResidualv3, [5, 2.7, 16, 0, 1, 1]],
        [1, Conv, [768, 1, 1]],
        [1, GlobalAvgPool, []],
        [1, "FixedConv", [6, 1, 1, null, 1, null]]
    ]